import { useEffect, useState } from "react";
import { Cpu, Clock, GitBranch } from "lucide-react";
import { useTranslation } from "react-i18next";

import { useClock } from "@/lib/wails";
// Bindings are generated by Wails from the Go services. Each service becomes
// a namespace of call functions under the matching package path.
import {
  SystemService,
  type SystemInfoResult,
} from "@/../bindings/github.com/ai-remote/workspace/internal/interfaces";

type SystemInfo = SystemInfoResult;

/**
 * Bottom status bar. Surfaces ambient context a developer expects at a glance:
 * app identity/version, runtime platform, and a live clock driven by the
 * backend `time` event (proof that Wails events are wired end-to-end).
 */
export function StatusBar() {
  const time = useClock();
  const [info, setInfo] = useState<SystemInfo | null>(null);
  const { t } = useTranslation();

  useEffect(() => {
    let cancelled = false;
    SystemService.SystemInfo()
      .then((res: SystemInfo) => {
        if (!cancelled) setInfo(res);
      })
      .catch(() => {
        /* Service binding may not be generated yet during early dev; ignore. */
      });
    return () => {
      cancelled = true;
    };
  }, []);

  return (
    <footer className="flex h-6 items-center justify-between border-t border-border bg-card px-3 text-xs text-muted-foreground">
      <div className="flex items-center gap-3">
        {info && (
          <>
            <span className="flex items-center gap-1">
              <GitBranch className="h-3 w-3" />
              {info.appName} v{info.version}
            </span>
            <span className="flex items-center gap-1">
              <Cpu className="h-3 w-3" />
              {info.platform}
            </span>
            <span className="hidden sm:inline">Go {info.goVersion}</span>
          </>
        )}
      </div>
      <div className="flex items-center gap-1">
        <Clock className="h-3 w-3" />
        <span className="tabular-nums">
          {time ?? t("status.connecting")}
        </span>
      </div>
    </footer>
  );
}
