// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AgentService exposes the AI agent to the frontend. Provider/model selection
 * is per chat call; provider management lives in ModelProviderService.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../application/models.js";

/**
 * ApproveToolCall resolves a pending approval request.
 */
export function ApproveToolCall(reqID: string, approved: boolean): $CancellablePromise<void> {
    return $Call.ByID(2824720777, reqID, approved);
}

/**
 * CancelChat aborts an ongoing agent chat.
 */
export function CancelChat(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(788153478, sessionID);
}

/**
 * EmitApproval sends an approval request to the frontend (implements
 * application.ApprovalEmitter). The frontend shows a dialog and calls
 * ApproveToolCall(reqID, approved).
 */
export function EmitApproval(req: application$0.ApprovalRequest): $CancellablePromise<void> {
    return $Call.ByID(3705362646, req);
}

/**
 * StartChat kicks off a streaming agent chat against the selected provider +
 * model. Output flows via events:
 *   agent:<sessionID>:chunk    — incremental LLM text
 *   agent:<sessionID>:toolcall — tool invocation start (id/tool/args)
 *   agent:<sessionID>:toolend  — tool invocation result (id/result)
 *   agent:<sessionID>:done     — chat completed
 *   agent:<sessionID>:error    — chat failed
 */
export function StartChat(sessionID: string, providerID: string, model: string, message: string): $CancellablePromise<void> {
    return $Call.ByID(960310724, sessionID, providerID, model, message);
}
