// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AgentService exposes the AI agent to the frontend. Provider/model selection
 * is per chat call; provider management lives in ModelProviderService.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApproveToolCall resolves a pending approval request.
 */
export function ApproveToolCall(reqID: string, approved: boolean): $CancellablePromise<void> {
    return $Call.ByID(2824720777, reqID, approved);
}

/**
 * CancelChat aborts an ongoing agent chat.
 */
export function CancelChat(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(788153478, sessionID);
}

/**
 * ClearHistory forgets a session's conversation memory (the frontend also
 * clears its local message list when the user clears the chat) and detaches
 * the session from its persisted conversation — the next turn starts a new
 * one.
 */
export function ClearHistory(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(2792127093, sessionID);
}

/**
 * DeleteConversation removes a persisted conversation. If it was the active
 * conversation of a session, that session's in-memory context is cleared too.
 */
export function DeleteConversation(conversationID: string): $CancellablePromise<void> {
    return $Call.ByID(3848825678, conversationID);
}

/**
 * EmitApproval sends an approval request to the frontend (implements
 * application.ApprovalEmitter). The frontend shows a dialog and calls
 * ApproveToolCall(reqID, approved).
 */
export function EmitApproval(req: application$0.ApprovalRequest): $CancellablePromise<void> {
    return $Call.ByID(3705362646, req);
}

/**
 * GetConversationMessages returns a conversation's user/assistant messages
 * in order.
 */
export function GetConversationMessages(conversationID: string): $CancellablePromise<$models.ConversationMessageDTO[] | null> {
    return $Call.ByID(4084462485, conversationID);
}

/**
 * ListConversations returns all persisted agent conversations (newest
 * first); the frontend filters by host.
 */
export function ListConversations(): $CancellablePromise<$models.ConversationDTO[] | null> {
    return $Call.ByID(4124442514);
}

/**
 * ResumeConversation points a terminal session at a persisted conversation
 * and replays it into the agent's multi-turn memory, so follow-up questions
 * keep context.
 */
export function ResumeConversation(sessionID: string, conversationID: string): $CancellablePromise<void> {
    return $Call.ByID(4110104030, sessionID, conversationID);
}

/**
 * SetSessionPolicy sets the approval policy a session's agent runs (the
 * dropdown in the agent input bar). "strict" asks for every WRITE/DANGEROUS
 * call; "auto_write" silently approves WRITE and keeps asking for DANGEROUS.
 * Unknown values normalize to strict.
 */
export function SetSessionPolicy(sessionID: string, policy: string): $CancellablePromise<void> {
    return $Call.ByID(1997586712, sessionID, policy);
}

/**
 * StartChat kicks off a streaming agent chat against the selected provider +
 * model. Output flows via events:
 *   agent:<sessionID>:chunk    — incremental LLM text
 *   agent:<sessionID>:toolcall — tool invocation start (id/tool/args)
 *   agent:<sessionID>:toolend  — tool invocation result (id/result)
 *   agent:<sessionID>:done     — chat completed
 *   agent:<sessionID>:error    — chat failed
 */
export function StartChat(sessionID: string, providerID: string, model: string, message: string): $CancellablePromise<void> {
    return $Call.ByID(960310724, sessionID, providerID, model, message);
}
