// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AgentService exposes the AI agent + LLM config to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApproveToolCall resolves a pending approval request.
 */
export function ApproveToolCall(reqID: string, approved: boolean): $CancellablePromise<void> {
    return $Call.ByID(2824720777, reqID, approved);
}

/**
 * CancelChat aborts an ongoing agent chat.
 */
export function CancelChat(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(788153478, sessionID);
}

/**
 * EmitApproval sends an approval request to the frontend (implements
 * application.ApprovalEmitter). The frontend shows a dialog and calls
 * ApproveToolCall(reqID, approved).
 */
export function EmitApproval(req: application$0.ApprovalRequest): $CancellablePromise<void> {
    return $Call.ByID(3705362646, req);
}

/**
 * GetLLMConfig returns the provider settings + whether an API key is stored.
 */
export function GetLLMConfig(): $CancellablePromise<$models.LLMConfigDTO> {
    return $Call.ByID(828267387);
}

/**
 * SetLLMConfig persists BaseURL/Model and stores/clears the API key.
 */
export function SetLLMConfig($in: $models.SetLLMConfigInput): $CancellablePromise<void> {
    return $Call.ByID(2998520687, $in);
}

/**
 * StartChat kicks off a streaming agent chat. Output flows via events:
 *   agent:<sessionID>:chunk   — incremental LLM text
 *   agent:<sessionID>:toolcall — tool invocation notice
 *   agent:<sessionID>:done    — chat completed
 *   agent:<sessionID>:error   — chat failed
 */
export function StartChat(sessionID: string, message: string): $CancellablePromise<void> {
    return $Call.ByID(960310724, sessionID, message);
}
