// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigService exposes the application ConfigService to the frontend.
 * (Same struct name on both sides is intentional; this lives in a different
 * package so it doesn't shadow the application interface.)
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

/**
 * GetAppConfig returns the persisted application configuration.
 * Returning the concrete domain.AppConfig lets Wails emit typed TS bindings.
 */
export function GetAppConfig(): $CancellablePromise<domain$0.AppConfig> {
    return $Call.ByID(1085469112);
}

/**
 * SetAppConfig persists a new configuration and broadcasts "config:changed"
 * to every window — settings are global but each window applies its own
 * chrome (theme/fonts/shortcuts), so aux windows like the standalone SFTP
 * window follow changes made anywhere.
 */
export function SetAppConfig(cfg: domain$0.AppConfig): $CancellablePromise<void> {
    return $Call.ByID(2422394692, cfg);
}
