// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DockerService exposes the Docker panel's data and control surface to the
 * frontend. All reads and actions run against the host behind the given
 * session (SSH exec channel) or the local docker CLI for local sessions.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

/**
 * ContainerAction performs a lifecycle action (start/stop/restart/pause/
 * unpause/kill) on one container.
 */
export function ContainerAction(sessionID: string, container: string, action: string): $CancellablePromise<string> {
    return $Call.ByID(2369218644, sessionID, container, action);
}

/**
 * GetContainerStats returns one-shot resource usage per running container.
 */
export function GetContainerStats(sessionID: string): $CancellablePromise<domain$0.DockerContainerStats[] | null> {
    return $Call.ByID(1995022483, sessionID);
}

/**
 * GetInfo returns the Docker overview (server version + counters) for a session.
 */
export function GetInfo(sessionID: string): $CancellablePromise<domain$0.DockerInfo> {
    return $Call.ByID(1355750061, sessionID);
}

/**
 * GetLogs returns the last `tail` timestamped log lines of one container.
 */
export function GetLogs(sessionID: string, container: string, tail: number): $CancellablePromise<string> {
    return $Call.ByID(1696773022, sessionID, container, tail);
}

/**
 * ListContainers returns the container list for a session (all=true includes
 * stopped containers).
 */
export function ListContainers(sessionID: string, all: boolean): $CancellablePromise<domain$0.DockerContainer[] | null> {
    return $Call.ByID(595444031, sessionID, all);
}

/**
 * ListImages returns the image list for a session.
 */
export function ListImages(sessionID: string): $CancellablePromise<domain$0.DockerImage[] | null> {
    return $Call.ByID(3101217033, sessionID);
}
