// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ExpertService exposes the digital-employee roster (运维专家/数字员工) to
 * the frontend: the chat-side pickers read it, the settings page manages it.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeleteExpert removes an expert; builtins are only dismissed and can be
 * restored by saving an expert with the same builtin id.
 */
export function DeleteExpert(id: string): $CancellablePromise<void> {
    return $Call.ByID(2050434340, id);
}

/**
 * GetExpert returns one expert including its full persona prompt (editor use).
 */
export function GetExpert(id: string): $CancellablePromise<$models.ExpertDTO> {
    return $Call.ByID(3615544669, id).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ListExperts returns the visible roster (dismissed builtins hidden).
 */
export function ListExperts(): $CancellablePromise<$models.ExpertDTO[]> {
    return $Call.ByID(1029338028).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SaveExpert creates or updates an expert and returns the stored row
 * (ids/flags are assigned server-side).
 */
export function SaveExpert(e: $models.ExpertDTO): $CancellablePromise<$models.ExpertDTO> {
    return $Call.ByID(2156068894, e).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ExpertDTO.createFrom;
const $$createType1 = $Create.Array($$createType0);
