// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ExpertService exposes the ops-expert roster (运维专家) to
 * the frontend: the chat-side pickers read it, the settings page manages it.
 * The transfer dependency (may be nil) backs expert package export/import.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeleteExpert removes an expert; builtins are only dismissed and can be
 * restored by saving an expert with the same builtin id.
 */
export function DeleteExpert(id: string): $CancellablePromise<void> {
    return $Call.ByID(2050434340, id);
}

/**
 * ExportExpert packages the expert plus its bound skill packs (bundled files
 * included) into a zip the user can archive or share.
 */
export function ExportExpert(id: string, zipPath: string): $CancellablePromise<$models.ExpertExportResultDTO> {
    return $Call.ByID(3522528793, id, zipPath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetExpert returns one expert including its full persona prompt (editor use).
 */
export function GetExpert(id: string): $CancellablePromise<$models.ExpertDTO> {
    return $Call.ByID(3615544669, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ImportExpert restores an expert package: the expert becomes a new custom
 * row (fresh id, builtin flag never travels) and the packaged skill packs
 * are installed, replacing same-name packs.
 */
export function ImportExpert(zipPath: string): $CancellablePromise<$models.ExpertDTO> {
    return $Call.ByID(3828834170, zipPath).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListExperts returns the visible roster (dismissed builtins hidden).
 */
export function ListExperts(): $CancellablePromise<$models.ExpertDTO[]> {
    return $Call.ByID(1029338028).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * SaveExpert creates or updates an expert and returns the stored row
 * (ids/flags are assigned server-side).
 */
export function SaveExpert(e: $models.ExpertDTO): $CancellablePromise<$models.ExpertDTO> {
    return $Call.ByID(2156068894, e).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ExpertExportResultDTO.createFrom;
const $$createType1 = $models.ExpertDTO.createFrom;
const $$createType2 = $Create.Array($$createType1);
