// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FaultReportService exposes the host-attached incident reports to the
 * frontend: list + filter on the 故障报告 page, save from the agent's
 * report-distillation dialog, status tracking and delete.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeleteReport removes one report.
 */
export function DeleteReport(id: string): $CancellablePromise<void> {
    return $Call.ByID(1416330564, id);
}

/**
 * GetReport returns one report with its full markdown body.
 */
export function GetReport(id: string): $CancellablePromise<$models.FaultReportDTO> {
    return $Call.ByID(1387666717, id).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ListReports returns reports matching the filter (newest first).
 */
export function ListReports(filter: $models.FaultReportFilterDTO): $CancellablePromise<$models.FaultReportDTO[]> {
    return $Call.ByID(127575808, filter).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SaveReport creates or updates a report (the frontend sends the reviewed
 * draft with host context; severity/status normalize server-side).
 */
export function SaveReport(dto: $models.FaultReportDTO): $CancellablePromise<$models.FaultReportDTO> {
    return $Call.ByID(827505862, dto).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SetReportStatus moves a report along its tracking lifecycle
 * (open → monitoring → resolved).
 */
export function SetReportStatus(id: string, status: string): $CancellablePromise<$models.FaultReportDTO> {
    return $Call.ByID(750180011, id, status).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.FaultReportDTO.createFrom;
const $$createType1 = $Create.Array($$createType0);
