// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HostService exposes host CRUD + connection testing to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateHost validates and stores a new host.
 */
export function CreateHost($in: $models.HostInputDTO): $CancellablePromise<$models.HostDTO> {
    return $Call.ByID(3920295711, $in);
}

/**
 * DeleteHost removes a host by id.
 */
export function DeleteHost(id: string): $CancellablePromise<void> {
    return $Call.ByID(4013598396, id);
}

/**
 * GetHost returns a single host by id.
 */
export function GetHost(id: string): $CancellablePromise<$models.HostDTO> {
    return $Call.ByID(3669425417, id);
}

/**
 * ListHosts returns all stored hosts.
 */
export function ListHosts(): $CancellablePromise<$models.HostDTO[] | null> {
    return $Call.ByID(910715712);
}

/**
 * TestConnection dials the host with the given credentials and reports
 * success/failure without keeping the session open.
 */
export function TestConnection(hostID: string, creds: $models.CredentialsDTO): $CancellablePromise<$models.TestConnectionResult> {
    return $Call.ByID(1230124561, hostID, creds);
}

/**
 * UpdateHost modifies an existing host.
 */
export function UpdateHost(id: string, $in: $models.HostInputDTO): $CancellablePromise<$models.HostDTO> {
    return $Call.ByID(2844861182, id, $in);
}
