// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HostService exposes host CRUD + connection testing to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateHost validates and stores a new host.
 */
export function CreateHost($in: $models.HostInputDTO): $CancellablePromise<$models.HostDTO> {
    return $Call.ByID(3920295711, $in).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DeleteHost removes a host by id.
 */
export function DeleteHost(id: string): $CancellablePromise<void> {
    return $Call.ByID(4013598396, id);
}

/**
 * GetHost returns a single host by id.
 */
export function GetHost(id: string): $CancellablePromise<$models.HostDTO> {
    return $Call.ByID(3669425417, id).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetRememberedCredentials reports which secrets are stored for a host. Used by
 * the edit dialog to show a "remembered" indicator without revealing values.
 */
export function GetRememberedCredentials(hostID: string): $CancellablePromise<$models.RememberedCredentialsDTO> {
    return $Call.ByID(501246757, hostID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListHosts returns all stored hosts.
 */
export function ListHosts(): $CancellablePromise<$models.HostDTO[]> {
    return $Call.ByID(910715712).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * SaveCredentials stores or clears remembered secrets for a host.
 * When remember is false, any existing secrets for this host are removed.
 * Password is stored for password auth; passphrase for key auth.
 */
export function SaveCredentials(hostID: string, creds: $models.CredentialsDTO, remember: boolean): $CancellablePromise<void> {
    return $Call.ByID(1355001190, hostID, creds, remember);
}

/**
 * SetAgentModel persists the host's last-used agent provider + model (hidden
 * preference; written by the agent panel, not the host edit form).
 */
export function SetAgentModel(hostID: string, providerID: string, model: string): $CancellablePromise<void> {
    return $Call.ByID(2353598437, hostID, providerID, model);
}

/**
 * TestConnection dials the host with the given credentials and reports
 * success/failure without keeping the session open. If the caller sends empty
 * credentials, remembered secrets from the OS vault are filled in first
 * (so "remember password" works for testing too, not just connecting).
 */
export function TestConnection(hostID: string, creds: $models.CredentialsDTO): $CancellablePromise<$models.TestConnectionResult> {
    return $Call.ByID(1230124561, hostID, creds).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * UpdateHost modifies an existing host.
 */
export function UpdateHost(id: string, $in: $models.HostInputDTO): $CancellablePromise<$models.HostDTO> {
    return $Call.ByID(2844861182, id, $in).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.HostDTO.createFrom;
const $$createType1 = $models.RememberedCredentialsDTO.createFrom;
const $$createType2 = $Create.Array($$createType0);
const $$createType3 = $models.TestConnectionResult.createFrom;
