// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * K8sService exposes the Kubernetes panel's data and control surface to the
 * frontend. All reads and actions run kubectl on the host behind the given
 * session (SSH exec channel) or the local kubectl CLI for local sessions.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

/**
 * ApplyResourceYAML submits an edited manifest via `kubectl apply -f -`
 * (stdin); identity guards ensure it lands on the object it was fetched from.
 */
export function ApplyResourceYAML(sessionID: string, kind: string, $namespace: string, name: string, doc: string): $CancellablePromise<string> {
    return $Call.ByID(4197438210, sessionID, kind, $namespace, name, doc);
}

/**
 * DeletePod removes one pod (returns as soon as the deletion is accepted).
 */
export function DeletePod(sessionID: string, $namespace: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(1612016935, sessionID, $namespace, name);
}

/**
 * GetClusterInfo returns the panel overview (versions, context, counters).
 */
export function GetClusterInfo(sessionID: string): $CancellablePromise<domain$0.K8sClusterInfo> {
    return $Call.ByID(1624512585, sessionID);
}

/**
 * GetPodLogs returns the last `tail` timestamped log lines of one pod
 * (optionally one of its containers — required for multi-container pods).
 */
export function GetPodLogs(sessionID: string, $namespace: string, pod: string, container: string, tail: number): $CancellablePromise<string> {
    return $Call.ByID(308423827, sessionID, $namespace, pod, container, tail);
}

/**
 * GetResourceYAML returns one resource's live manifest for the YAML viewer
 * (deployment/statefulset/daemonset/pod/service; concrete namespace required).
 */
export function GetResourceYAML(sessionID: string, kind: string, $namespace: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(4152169066, sessionID, kind, $namespace, name);
}

/**
 * ListEvents returns recent events, newest first.
 */
export function ListEvents(sessionID: string, $namespace: string): $CancellablePromise<domain$0.K8sEvent[] | null> {
    return $Call.ByID(468827386, sessionID, $namespace);
}

/**
 * ListNamespaces returns the namespaces for the panel's scope picker.
 */
export function ListNamespaces(sessionID: string): $CancellablePromise<domain$0.K8sNamespace[] | null> {
    return $Call.ByID(2512034963, sessionID);
}

/**
 * ListNodes returns the cluster nodes (read-only).
 */
export function ListNodes(sessionID: string): $CancellablePromise<domain$0.K8sNode[] | null> {
    return $Call.ByID(1026463924, sessionID);
}

/**
 * ListPods returns the pod rows for the namespace scope.
 */
export function ListPods(sessionID: string, $namespace: string): $CancellablePromise<domain$0.K8sPod[] | null> {
    return $Call.ByID(2414153711, sessionID, $namespace);
}

/**
 * ListServices returns the service rows for the namespace scope.
 */
export function ListServices(sessionID: string, $namespace: string): $CancellablePromise<domain$0.K8sServiceInfo[] | null> {
    return $Call.ByID(706378611, sessionID, $namespace);
}

/**
 * ListWorkloads returns one workload kind's rows (deployments/statefulsets/
 * daemonsets). An empty namespace means all namespaces.
 */
export function ListWorkloads(sessionID: string, kind: string, $namespace: string): $CancellablePromise<domain$0.K8sWorkload[] | null> {
    return $Call.ByID(1804329619, sessionID, kind, $namespace);
}

/**
 * WorkloadAction performs a lifecycle action on one workload (scale with
 * replicas for deployment/statefulset; rollout restart for all kinds).
 */
export function WorkloadAction(sessionID: string, kind: string, $namespace: string, name: string, action: string, replicas: number): $CancellablePromise<string> {
    return $Call.ByID(2208583336, sessionID, kind, $namespace, name, action, replicas);
}
