// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * KeyManagerService exposes the 密钥管理器 to the frontend: managed SSH keys
 * stored under <数据目录>/keys (generate / import / export / delete).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeleteKey removes a managed key (registry + private file).
 */
export function DeleteKey(id: string): $CancellablePromise<void> {
    return $Call.ByID(2805538061, id);
}

/**
 * ExportKey copies the private key to targetPath (0600) and writes the
 * matching .pub next to it (when derivable). Returns the .pub path (empty
 * for encrypted keys).
 */
export function ExportKey(id: string, targetPath: string): $CancellablePromise<string> {
    return $Call.ByID(3017488238, id, targetPath);
}

/**
 * GenerateKey creates a key pair and registers it. Returns the entry and
 * the authorized_keys-format public line (for copying to servers).
 */
export function GenerateKey(req: $models.GenerateKeyRequestDTO): $CancellablePromise<[$models.ManagedKeyDTO, string]> {
    return $Call.ByID(2959909989, req);
}

/**
 * ImportKey registers an existing private key file.
 */
export function ImportKey(req: $models.ImportKeyRequestDTO): $CancellablePromise<$models.ManagedKeyDTO> {
    return $Call.ByID(3312635047, req);
}

/**
 * ListKeys returns every managed key.
 */
export function ListKeys(): $CancellablePromise<$models.ManagedKeyDTO[] | null> {
    return $Call.ByID(3231029269);
}
