// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MCPService exposes the local MCP server's runtime state to the settings
 * UI. Enabling/port changes go through the normal config flow
 * (ConfigService.SetAppConfig → Server.ApplyConfig); this service adds
 * read-only status plus token rotation.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

/**
 * RegenerateToken replaces the bearer token — existing client configs must
 * be updated — persists it, and returns the refreshed status.
 */
export function RegenerateToken(): $CancellablePromise<domain$0.MCPStatus> {
    return $Call.ByID(3252352706).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Status returns the MCP server's runtime state (running/port/token/URL/
 * last error) for the settings page.
 */
export function Status(): $CancellablePromise<domain$0.MCPStatus> {
    return $Call.ByID(2207773045).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = domain$0.MCPStatus.createFrom;
