// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConversationDTO is a persisted agent conversation for the history list.
 */
export interface ConversationDTO {
    "id": string;
    "hostId": string;
    "hostName": string;
    "title": string;
    "updatedAt": string;
    "messageCount": number;
}

/**
 * ConversationMessageDTO is one persisted user/assistant message.
 */
export interface ConversationMessageDTO {
    /**
     * "user" | "assistant"
     */
    "role": string;
    "content": string;
}

/**
 * CredentialsDTO carries connect-time secret material supplied by the UI.
 * Never persisted.
 */
export interface CredentialsDTO {
    "password"?: string;
    "keyPath"?: string;
    "keyPassphrase"?: string;
    "useAgent"?: boolean;
}

/**
 * FileEntryDTO is the frontend-facing remote filesystem entry.
 */
export interface FileEntryDTO {
    "name": string;
    "size": number;
    "mode": string;
    "modTime": string;
    "isDir": boolean;
}

/**
 * HostDTO is the frontend-facing host representation. It mirrors domain.Host
 * but exposes authType as a plain string and omits internal timestamps that
 * the UI doesn't need.
 */
export interface HostDTO {
    "id": string;
    "name": string;
    "host": string;
    "port": number;
    "username": string;
    "authType": string;
    "keyPath"?: string;
    "hasRememberedSecret": boolean;

    /**
     * per-host terminal colour scheme id
     */
    "terminalTheme": string;

    /**
     * per-host override; "" = follow settings
     */
    "terminalFont": string;

    /**
     * per-host override; 0 = follow settings
     */
    "terminalFontSize": number;
    "group": string;
    "tags": string[] | null;

    /**
     * detected distro id; read-only, never editable
     */
    "os": string;

    /**
     * Last-used agent model preference; read-only for the host form, written
     * via SetAgentModel by the agent panel.
     */
    "agentProviderId": string;
    "agentModel": string;
}

/**
 * HostInputDTO is what the frontend sends to create/update a host.
 */
export interface HostInputDTO {
    "name": string;
    "host": string;
    "port": number;
    "username": string;
    "authType": string;
    "keyPath"?: string;
    "terminalTheme": string;
    "terminalFont": string;
    "terminalFontSize": number;
    "group": string;
    "tags": string[] | null;
}

/**
 * LocalIPResult carries the machine's primary local IP address.
 */
export interface LocalIPResult {
    "ip": string;
}

/**
 * ModelProviderDTO carries a provider to the frontend — never the API key.
 */
export interface ModelProviderDTO {
    "id": string;
    "name": string;
    "baseUrl": string;
    "models": string[] | null;
    "enabled": boolean;
    "hasApiKey": boolean;
}

/**
 * OpenSessionRequest carries what the frontend needs to start a terminal.
 */
export interface OpenSessionRequest {
    "hostId": string;
    "creds": CredentialsDTO;
    "size": PtySizeDTO;
}

/**
 * OpenSessionResult returns the new session id to the frontend.
 */
export interface OpenSessionResult {
    "sessionId": string;
}

/**
 * PtySizeDTO is the initial terminal dimensions.
 */
export interface PtySizeDTO {
    "cols": number;
    "rows": number;
}

/**
 * RememberedCredentialsDTO tells the UI whether remembered secrets exist.
 * The secret values are deliberately NOT returned — the vault is read at
 * connect time on the backend, never shipped to the frontend.
 */
export interface RememberedCredentialsDTO {
    "hasPassword": boolean;
    "hasPassphrase": boolean;
}

/**
 * SaveProviderInput is what the frontend sends to create/update a provider.
 */
export interface SaveProviderInput {
    /**
     * empty = create
     */
    "id": string;
    "name": string;
    "baseUrl": string;
    "models": string[] | null;
    "enabled": boolean;

    /**
     * empty = keep existing; " " = clear
     */
    "apiKey": string;
}

/**
 * SystemInfoResult mirrors what the frontend StatusBar displays.
 * Field names become the TS property names in generated bindings.
 */
export interface SystemInfoResult {
    "appName": string;
    "version": string;
    "platform": string;
    "goVersion": string;
}

/**
 * TestConnectionResult reports a connection attempt outcome to the UI.
 */
export interface TestConnectionResult {
    "ok": boolean;
    "msg": string;
}

/**
 * TestProviderInput addresses a provider for testing / model fetching. Empty
 * BaseURL or APIKey with an ID present falls back to the stored values.
 */
export interface TestProviderInput {
    "id": string;
    "baseUrl": string;
    "apiKey": string;

    /**
     * optional; defaults to the first recorded model
     */
    "model": string;
}
