// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ModelProviderService exposes LLM provider management to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeleteProvider removes a provider and its stored API key.
 */
export function DeleteProvider(id: string): $CancellablePromise<void> {
    return $Call.ByID(3386393949, id);
}

/**
 * FetchModels lists the models a provider exposes via its /models endpoint.
 */
export function FetchModels($in: $models.TestProviderInput): $CancellablePromise<string[]> {
    return $Call.ByID(2538470563, $in).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ListProviders returns all providers with their enabled state and whether an
 * API key is stored.
 */
export function ListProviders(): $CancellablePromise<$models.ModelProviderDTO[]> {
    return $Call.ByID(2664383435).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * SaveProvider creates or updates a provider.
 */
export function SaveProvider($in: $models.SaveProviderInput): $CancellablePromise<void> {
    return $Call.ByID(3549763003, $in);
}

/**
 * TestProvider verifies the endpoint with a minimal chat completion.
 */
export function TestProvider($in: $models.TestProviderInput): $CancellablePromise<$models.TestConnectionResult> {
    return $Call.ByID(1804890310, $in).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $models.ModelProviderDTO.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.TestConnectionResult.createFrom;
