// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SystemInfoResult mirrors what the frontend StatusBar displays.
 * Field names become the TS property names in generated bindings.
 */
export interface SystemInfoResult {
    "appName": string;
    "version": string;
    "platform": string;
    "goVersion": string;
}
