// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MonitorService exposes host metrics collection to the frontend. Collection
 * runs over an existing terminal session's SSH connection (sessionID = the
 * tab's session), so no extra dial or credentials are involved.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

/**
 * GetOverview returns the host overview snapshot for a live SSH session.
 */
export function GetOverview(sessionID: string): $CancellablePromise<domain$0.MonitorOverview> {
    return $Call.ByID(725328748, sessionID).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetPorts returns the listening-socket list for a live SSH session.
 */
export function GetPorts(sessionID: string): $CancellablePromise<domain$0.MonitorPort[]> {
    return $Call.ByID(2889349069, sessionID).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetProcesses returns the live process list for a live SSH session.
 */
export function GetProcesses(sessionID: string): $CancellablePromise<domain$0.MonitorProcess[]> {
    return $Call.ByID(1596473676, sessionID).then(($result: any) => {
        return $$createType4($result);
    });
}

// Private type creation functions
const $$createType0 = domain$0.MonitorOverview.createFrom;
const $$createType1 = domain$0.MonitorPort.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = domain$0.MonitorProcess.createFrom;
const $$createType4 = $Create.Array($$createType3);
