// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SftpService exposes remote file operations to the frontend.
 * 
 * The frontend passes empty credentials: the backend resolves remembered
 * secrets from the OS vault (Phase 5 SecretStore). If no remembered secret
 * exists, the operation fails with an auth error the UI surfaces.
 * 
 * Downloads/uploads emit per-transfer progress events named
 * "sftp:transfer:<id>" (Go → JS); the frontend supplies the id.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeleteFile removes a remote file or empty directory.
 */
export function DeleteFile(hostID: string, remotePath: string): $CancellablePromise<void> {
    return $Call.ByID(3253740251, hostID, remotePath);
}

/**
 * DownloadFile reads a remote file and returns its bytes. Progress events are
 * emitted on "sftp:transfer:<transferID>" while the read runs.
 */
export function DownloadFile(hostID: string, remotePath: string, transferID: string): $CancellablePromise<string | null> {
    return $Call.ByID(3243520916, hostID, remotePath, transferID);
}

/**
 * ListDir returns the entries of a remote directory.
 */
export function ListDir(hostID: string, dir: string): $CancellablePromise<$models.FileEntryDTO[] | null> {
    return $Call.ByID(358301269, hostID, dir);
}

/**
 * Mkdir creates a remote directory.
 */
export function Mkdir(hostID: string, remotePath: string): $CancellablePromise<void> {
    return $Call.ByID(1479971433, hostID, remotePath);
}

/**
 * RenameFile renames/moves a remote entry.
 */
export function RenameFile(hostID: string, oldPath: string, newPath: string): $CancellablePromise<void> {
    return $Call.ByID(3195865754, hostID, oldPath, newPath);
}

/**
 * UploadFile writes data to a remote path. Progress events are emitted on
 * "sftp:transfer:<transferID>" while the write runs.
 */
export function UploadFile(hostID: string, remotePath: string, data: string | null, transferID: string): $CancellablePromise<void> {
    return $Call.ByID(2314891305, hostID, remotePath, data, transferID);
}
