// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SftpService exposes remote file operations to the frontend.
 * 
 * The frontend passes empty credentials: the backend resolves remembered
 * secrets from the OS vault (Phase 5 SecretStore). If no remembered secret
 * exists, the operation fails with an auth error the UI surfaces.
 * 
 * Streaming transfers (StartDownload/StartUpload) run asynchronously in a
 * backend goroutine: progress events arrive on "sftp:transfer:<id>" and a
 * terminal event on "sftp:transfer:<id>:end" (data = "" on success,
 * "cancelled", or the error text). CancelTransfer aborts by id.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelTransfer aborts a running streaming transfer by its id.
 */
export function CancelTransfer(transferID: string): $CancellablePromise<void> {
    return $Call.ByID(383603475, transferID);
}

/**
 * DeleteFile removes a remote file or empty directory.
 */
export function DeleteFile(hostID: string, remotePath: string): $CancellablePromise<void> {
    return $Call.ByID(3253740251, hostID, remotePath);
}

/**
 * DownloadFile reads a remote file and returns its bytes. Progress events are
 * emitted on "sftp:transfer:<transferID>" while the read runs.
 */
export function DownloadFile(hostID: string, remotePath: string, transferID: string): $CancellablePromise<string | null> {
    return $Call.ByID(3243520916, hostID, remotePath, transferID);
}

/**
 * ListDir returns the entries of a remote directory.
 */
export function ListDir(hostID: string, dir: string): $CancellablePromise<$models.FileEntryDTO[] | null> {
    return $Call.ByID(358301269, hostID, dir);
}

/**
 * LocalExists reports whether a local path exists — the download-side
 * same-name conflict check (the UI offers overwrite vs auto-rename).
 */
export function LocalExists(path: string): $CancellablePromise<boolean> {
    return $Call.ByID(2959701953, path);
}

/**
 * Mkdir creates a remote directory.
 */
export function Mkdir(hostID: string, remotePath: string): $CancellablePromise<void> {
    return $Call.ByID(1479971433, hostID, remotePath);
}

/**
 * RenameFile renames/moves a remote entry.
 */
export function RenameFile(hostID: string, oldPath: string, newPath: string): $CancellablePromise<void> {
    return $Call.ByID(3195865754, hostID, oldPath, newPath);
}

/**
 * StartDownload streams a remote file to a local path chosen via the native
 * save dialog. Returns immediately; progress and completion arrive as
 * events (see the type comment). The remote size is pre-checked against the
 * configured ceiling — an oversized file fails with the limit named.
 */
export function StartDownload(hostID: string, remotePath: string, localPath: string, transferID: string): $CancellablePromise<void> {
    return $Call.ByID(245680938, hostID, remotePath, localPath, transferID);
}

/**
 * StartUpload streams a local file (native-open dialog path) to a remote
 * path, staging via ".airw-part" and renaming on completion.
 */
export function StartUpload(hostID: string, localPath: string, remotePath: string, transferID: string): $CancellablePromise<void> {
    return $Call.ByID(2542626223, hostID, localPath, remotePath, transferID);
}

/**
 * UploadClipboardImage decodes base64 image data and stores it as /tmp/<name>
 * on the host, returning the path written. An empty hostID stores the file in
 * the LOCAL temp dir instead (local terminal sessions) — the path is inserted
 * into the terminal so the user can reference it right away.
 */
export function UploadClipboardImage(hostID: string, name: string, dataB64: string): $CancellablePromise<string> {
    return $Call.ByID(3372244996, hostID, name, dataB64);
}

/**
 * UploadFile writes data to a remote path. Progress events are emitted on
 * "sftp:transfer:<transferID>" while the write runs.
 */
export function UploadFile(hostID: string, remotePath: string, data: string | null, transferID: string): $CancellablePromise<void> {
    return $Call.ByID(2314891305, hostID, remotePath, data, transferID);
}
