// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SystemService exposes ambient runtime info to the UI. Phase 6's MCP
 * `system_info` tool will reuse this.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * SystemInfo returns the runtime info shown in the StatusBar.
 */
export function SystemInfo(): $CancellablePromise<$models.SystemInfoResult> {
    return $Call.ByID(1969377999);
}
