// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TunnelService exposes SSH tunnel control + status to the frontend. State
 * changes stream on the "tunnel:status" event (the panel keeps a live view);
 * ListTunnels returns the full snapshot (initial load).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckTunnelPorts reports which of the requested LOCAL listen ports are
 * already occupied — the save-time conflict pre-check for the host form.
 * Ports bound by this host's own tunnels are exempt (they belong to the host
 * being edited and are reconciled on save); anything else holding the port —
 * another process, or another host's tunnel — is reported.
 */
export function CheckTunnelPorts(hostID: string, ports: number[] | null): $CancellablePromise<number[] | null> {
    return $Call.ByID(1171169755, hostID, ports);
}

/**
 * EmitStatus forwards a manager status update onto the Wails event bus
 * (wired as the manager's emitter in ServiceStartup).
 */
export function EmitStatus(s: domain$0.TunnelStatus): $CancellablePromise<void> {
    return $Call.ByID(914667492, s);
}

/**
 * ListTunnels returns the status of every known tunnel (all hosts).
 */
export function ListTunnels(): $CancellablePromise<$models.TunnelStatusDTO[] | null> {
    return $Call.ByID(1427034688);
}

/**
 * StartTunnel ensures the host's tunnels are running per its saved rules,
 * resolving remembered credentials from the OS vault for the connections.
 */
export function StartTunnel(hostID: string): $CancellablePromise<void> {
    return $Call.ByID(555606337, hostID);
}

/**
 * StopTunnel stops the host's tunnels (the rules stay; the next session on
 * the host or a manual start brings them back).
 */
export function StopTunnel(hostID: string): $CancellablePromise<void> {
    return $Call.ByID(3368897255, hostID);
}
