// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WindowService opens auxiliary app windows from the frontend. Currently:
 * the standalone SFTP workbench window (dual-pane local ⋅ remote file
 * manager), one per host — re-opening focuses the existing window.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * OpenSftpWindow opens the dual-pane SFTP workbench for the host in a new
 * native window. The window loads "#/sftp-window?host=<id>" — the frontend
 * router mounts the workbench (instead of the main app shell) when it sees
 * that hash. A second call for the same host focuses the existing window.
 */
export function OpenSftpWindow(hostID: string): $CancellablePromise<void> {
    return $Call.ByID(2359881606, hostID);
}
