// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AgentConfig holds the AI agent runtime tunables exposed in global
 * settings. Zero values mean "use the built-in default" (filled in by the
 * config service), so an absent block in an older settings row upgrades
 * cleanly.
 */
export interface AgentConfig {
    /**
     * MaxSteps bounds the ReAct loop per turn (model + tool node executions;
     * one tool round ≈ 2 steps). Default 100.
     */
    "maxSteps": number;

    /**
     * HistoryTurns caps how many past (user, assistant) turns are replayed
     * as conversation memory. Default 40.
     */
    "historyTurns": number;

    /**
     * ToolOutputLimitKB caps a single tool result fed back to the model
     * (head+tail kept, middle elided). Default 64.
     */
    "toolOutputLimitKB": number;

    /**
     * CustomInstructions is appended to the built-in system prompt on every
     * turn — standing preferences, host context, tone. Empty = built-in
     * prompt only.
     */
    "customInstructions": string;
}

/**
 * AppConfig is the persisted application configuration.
 * Stored in the `settings` table (Phase 1); sensitive fields would route
 * through SecretStore per AGENT.md §9.
 */
export interface AppConfig {
    "securityMode": SecurityMode;
    "defaultShell": string;

    /**
     * "light" | "dark" | "auto"
     */
    "theme": string;

    /**
     * interface font family name
     */
    "uiFont": string;

    /**
     * interface font size in px
     */
    "fontSize": number;

    /**
     * CJK (Chinese) font family name
     */
    "cjkFont": string;

    /**
     * Global terminal appearance defaults. Per-host values ("" / 0) fall back
     * to these; they are also where the appearance dialog persists changes
     * made in a LOCAL terminal tab (no host record to write to).
     * "" / 0 = built-in defaults (cobalt2 / Cascadia stack / 13px).
     */
    "terminalTheme": string;
    "terminalFont": string;
    "terminalFontSize": number;

    /**
     * Terminal content highlighting (http/https links, ERROR/WARN keywords).
     * Inverted flags: an older settings row without the fields keeps both
     * highlights enabled — the out-of-box default.
     */
    "disableLinkHighlight": boolean;
    "disableKeywordHighlight": boolean;

    /**
     * User-defined highlight rules: a regex and the color scheme used to
     * paint its matches. Invalid patterns are skipped by the renderer.
     */
    "highlightRules"?: HighlightRule[] | null;

    /**
     * AI agent provider config (API key in SecretStore)
     */
    "llm": LLMConfig;

    /**
     * Keyboard shortcut overrides (Xshell-style). Key = command id
     * ("terminal.copy"), value = binding string ("Ctrl+Shift+C"). Only entries
     * the user changed from the default are stored; nil/empty = all defaults.
     */
    "shortcuts"?: { [_ in string]?: string } | null;

    /**
     * Middle-click behavior on terminal panes (Xshell-style): "none" |
     * "pasteSelection" (default) | "pasteClipboard" | "sendEnter" |
     * "contextMenu".
     */
    "middleClickAction": string;

    /**
     * Host monitor panel auto-refresh interval in seconds (0 = default 60).
     */
    "monitorIntervalSeconds": number;

    /**
     * AI agent runtime tunables (提示词 / 最大步数等, user-adjustable).
     */
    "agent": AgentConfig;

    /**
     * SFTP file-transfer tunables (streaming chunk size + size ceilings).
     */
    "transfer": TransferConfig;
}

/**
 * DockerContainer is one container row (`docker ps [-a] --format json`).
 */
export interface DockerContainer {
    "id": string;
    "names": string;
    "image": string;

    /**
     * "running" | "exited" | "paused" | "created" | "restarting" | "dead"
     */
    "state": string;

    /**
     * human status incl. health/uptime ("Up 2 hours (healthy)")
     */
    "status": string;

    /**
     * "0.0.0.0:80->80/tcp, [::]:80->80/tcp"
     */
    "ports": string;
    "createdAt": string;
}

/**
 * DockerContainerStats is one container's live resource usage
 * (`docker stats --no-stream --format json`).
 */
export interface DockerContainerStats {
    "containerId": string;
    "name": string;

    /**
     * "1.24%"
     */
    "cpuPercent": string;

    /**
     * "6.41%"
     */
    "memPercent": string;

    /**
     * "123.4MiB / 3.84GiB"
     */
    "memUsage": string;

    /**
     * "1.2kB / 3.4kB"
     */
    "netIO": string;

    /**
     * "0B / 12.6kB"
     */
    "blockIO": string;
    "pids": string;
}

/**
 * DockerImage is one image row (`docker images --format json`).
 */
export interface DockerImage {
    "repository": string;
    "tag": string;
    "id": string;

    /**
     * "2 weeks ago"
     */
    "createdSince": string;

    /**
     * "104MB"
     */
    "size": string;
}

/**
 * DockerInfo is the panel overview: `docker version` server section merged
 * with the counters from `docker info`.
 */
export interface DockerInfo {
    "version": string;
    "apiVersion": string;
    "osType": string;
    "arch": string;
    "kernelVersion": string;
    "containersRunning": number;
    "containersPaused": number;
    "containersStopped": number;
    "images": number;
    "dockerRootDir": string;
}

/**
 * DockerNetwork is one network row (`docker network ls --format json`).
 */
export interface DockerNetwork {
    "id": string;
    "name": string;

    /**
     * "bridge" | "host" | "overlay" | "none" | …
     */
    "driver": string;

    /**
     * "local" | "swarm"
     */
    "scope": string;
    "internal": boolean;
    "ipv6": boolean;
}

/**
 * DockerNetworkContainer is one endpoint attached to a network.
 */
export interface DockerNetworkContainer {
    "name": string;
    "ipv4Address": string;
    "ipv6Address": string;
}

/**
 * DockerNetworkDetail is `docker network inspect --format json`: the row
 * fields plus IPAM pools and the attached containers.
 */
export interface DockerNetworkDetail {
    "id": string;
    "name": string;
    "driver": string;
    "scope": string;
    "internal": boolean;
    "enableIpv6": boolean;
    "subnets": DockerNetworkSubnet[] | null;
    "containers": DockerNetworkContainer[] | null;
}

/**
 * DockerNetworkSubnet is one IPAM pool of a network.
 */
export interface DockerNetworkSubnet {
    "subnet": string;
    "gateway": string;
}

/**
 * HighlightRule is a user-defined terminal content highlight: a regular
 * expression and the color scheme used to paint its matches. The regex is
 * JavaScript-flavored (compiled in the renderer); invalid patterns are
 * ignored, never breaking the terminal.
 */
export interface HighlightRule {
    "pattern": string;

    /**
     * Color scheme id from the highlight palette (red/orange/yellow/green/
     * cyan/blue/purple/pink).
     */
    "color": string;
}

/**
 * LLMConfig holds the non-sensitive LLM provider settings. The API Key is
 * stored in the OS vault (SecretStore), never here.
 * 
 * Deprecated: superseded by ModelProvider (multi-provider). Kept only so the
 * legacy single-provider config can be migrated on first run.
 */
export interface LLMConfig {
    /**
     * e.g. "https://api.openai.com/v1" or a compatible endpoint
     */
    "baseUrl": string;

    /**
     * e.g. "gpt-4o", "deepseek-chat"
     */
    "model": string;
}

/**
 * MonitorDiskUsage is one mounted filesystem's usage.
 */
export interface MonitorDiskUsage {
    "device": string;
    "mount": string;
    "totalKb": number;
    "usedKb": number;
    "usedPercent": number;
}

/**
 * MonitorOverview is the host snapshot shown in the monitor panel's
 * Overview tab. Rates are computed from two samples taken ~1s apart.
 */
export interface MonitorOverview {
    "cpuPercent": number;
    "cpuModel": string;
    "cpuCores": number;
    "load1": number;
    "load5": number;
    "load15": number;
    "uptimeSeconds": number;
    "kernel": string;
    "memTotalKb": number;
    "memUsedKb": number;
    "memUsedPercent": number;
    "swapTotalKb": number;
    "swapUsedKb": number;
    "disks": MonitorDiskUsage[] | null;
    "netRxBytesPerSec": number;
    "netTxBytesPerSec": number;
    "processTotal": number;
    "processRunning": number;
    "tcpStates": MonitorTCPState[] | null;
}

/**
 * MonitorPort is one listening TCP socket (or a group of identical binds).
 */
export interface MonitorPort {
    /**
     * "tcp" | "tcp6"
     */
    "proto": string;

    /**
     * decoded bind address
     */
    "address": string;
    "port": number;

    /**
     * sockets with this identical bind (SO_REUSEPORT etc.)
     */
    "count": number;
}

/**
 * MonitorProcess is one remote process with a live (sampled) CPU usage.
 */
export interface MonitorProcess {
    "pid": number;
    "name": string;
    "commandLine": string;
    "cpuPercent": number;
    "rssKb": number;
}

/**
 * MonitorTCPState is one TCP connection-state histogram bucket.
 */
export interface MonitorTCPState {
    /**
     * "ESTABLISHED", "LISTEN", "TIME_WAIT", …
     */
    "state": string;
    "count": number;
}

/**
 * Permission tier (AGENT.md §14). READ runs silently; WRITE prompts;
 * DANGEROUS requires explicit user approval.
 */
export enum Permission {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PermissionRead = "read",
    PermissionWrite = "write",
    PermissionDangerous = "dangerous",
};

/**
 * SecurityMode governs how credentials are handled (AGENT.md §10).
 */
export enum SecurityMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SecurityConvenience = "convenience",

    /**
     * default
     */
    SecurityBalanced = "balanced",
    SecuritySecure = "secure",
};

/**
 * TransferConfig holds the SFTP streaming-transfer tunables exposed in
 * global settings. Zero values mean "use the built-in default" (filled in
 * by the config service). Size ceilings exist to protect the user from
 * accidental giant transfers, not from memory pressure — transfers stream
 * with a fixed buffer regardless of file size.
 */
export interface TransferConfig {
    /**
     * ChunkKB is the streaming chunk size in KB (also the progress-event
     * granularity). Default 256.
     */
    "chunkKb": number;

    /**
     * MaxUploadMB caps a single upload. Default 4096; raise it in settings
     * for effectively-unlimited transfers (0 falls back to the default).
     */
    "maxUploadMb": number;

    /**
     * MaxDownloadMB caps a single download. Default 4096.
     */
    "maxDownloadMb": number;
}

/**
 * TunnelConfig is a per-host SSH tunnel definition, edited in the host
 * settings and persisted with the host (no secrets inside — the tunnel
 * authenticates with the host's credentials).
 */
export interface TunnelConfig {
    "enabled": boolean;
    "type": TunnelType;

    /**
     * local/dynamic: local machine; remote: the SSH server
     */
    "listenPort": number;

    /**
     * Listen bind address: the local machine for local/dynamic, the server
     * for remote. "" = 127.0.0.1 (only the tunnel's own machine); "0.0.0.0"
     * exposes the listener to the network.
     */
    "bindHost"?: string;

    /**
     * Forward target. local: resolved from the SERVER's side (e.g. its
     * loopback MySQL); remote: resolved from the LOCAL machine's side.
     */
    "targetHost"?: string;
    "targetPort"?: number;
}

/**
 * TunnelState is the lifecycle state of a running (or attempted) tunnel.
 */
export enum TunnelState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * not running (never started or stopped by user)
     */
    TunnelStopped = "stopped",

    /**
     * dialing the first connection
     */
    TunnelStarting = "starting",

    /**
     * SSH up, listener serving
     */
    TunnelConnected = "connected",

    /**
     * connection lost; backing off before redial
     */
    TunnelReconnecting = "reconnecting",

    /**
     * fatal setup problem (e.g. port already in use)
     */
    TunnelError = "error",
};

/**
 * TunnelStatus is the manager's view of one host's tunnel — pushed to the
 * frontend on every change and returned by ListTunnels. One host can have
 * several; Key identifies the rule within the host.
 */
export interface TunnelStatus {
    "hostId": string;
    "hostName": string;

    /**
     * rule identity (TunnelConfig.Key)
     */
    "key": string;
    "config": TunnelConfig;
    "state": TunnelState;

    /**
     * human-readable, shown in the panel
     */
    "lastError"?: string;

    /**
     * consecutive failed dials in the current cycle
     */
    "retries": number;
}

/**
 * TunnelType selects how an SSH tunnel exposes a network on the far side —
 * the three forms Xshell offers (AGENT.md §16.5).
 */
export enum TunnelType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * TunnelLocal forwards a local listen port to (TargetHost, TargetPort)
     * as seen from the SSH server — `ssh -L`. Use-case: reach a database or
     * web panel bound to the server's internal/loopback interface.
     */
    TunnelLocal = "local",

    /**
     * TunnelRemote is the reverse: the SSH SERVER listens on
     * (BindHost, ListenPort) and every connection there is carried back to
     * (TargetHost, TargetPort) as seen from the local machine — `ssh -R`.
     * Use-case: expose a service running on your machine to the server (or
     * its network).
     */
    TunnelRemote = "remote",

    /**
     * TunnelDynamic exposes a SOCKS5 proxy on (BindHost, ListenPort) whose
     * connects originate from the SSH server — `ssh -D`.
     */
    TunnelDynamic = "dynamic",
};
