// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppConfig is the persisted application configuration.
 * Stored in the `settings` table (Phase 1); sensitive fields would route
 * through SecretStore per AGENT.md §9.
 */
export interface AppConfig {
    "securityMode": SecurityMode;
    "defaultShell": string;
    "theme": string;
}

/**
 * SecurityMode governs how credentials are handled (AGENT.md §10).
 */
export enum SecurityMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SecurityConvenience = "convenience",

    /**
     * default
     */
    SecurityBalanced = "balanced",
    SecuritySecure = "secure",
};
