// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AgentConfig holds the AI agent runtime tunables exposed in global
 * settings. Zero values mean "use the built-in default" (filled in by the
 * config service), so an absent block in an older settings row upgrades
 * cleanly.
 */
export class AgentConfig {
    /**
     * MaxSteps bounds the ReAct loop per turn (model + tool node executions;
     * one tool round ≈ 2 steps). Default 100.
     */
    "maxSteps": number;

    /**
     * HistoryTurns caps how many past (user, assistant) turns are replayed
     * as conversation memory. Default 40.
     */
    "historyTurns": number;

    /**
     * ToolOutputLimitKB caps a single tool result fed back to the model
     * (head+tail kept, middle elided). Default 64.
     */
    "toolOutputLimitKB": number;

    /**
     * CustomInstructions is appended to the built-in system prompt on every
     * turn — standing preferences, host context, tone. Empty = built-in
     * prompt only.
     */
    "customInstructions": string;

    /** Creates a new AgentConfig instance. */
    constructor($$source: Partial<AgentConfig> = {}) {
        if (!("maxSteps" in $$source)) {
            this["maxSteps"] = 0;
        }
        if (!("historyTurns" in $$source)) {
            this["historyTurns"] = 0;
        }
        if (!("toolOutputLimitKB" in $$source)) {
            this["toolOutputLimitKB"] = 0;
        }
        if (!("customInstructions" in $$source)) {
            this["customInstructions"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): AgentConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AgentConfig($$parsedSource as Partial<AgentConfig>);
    }
}

/**
 * AppConfig is the persisted application configuration.
 * Stored in the `settings` table (Phase 1); sensitive fields would route
 * through SecretStore per AGENT.md §9.
 */
export class AppConfig {
    "securityMode": SecurityMode;
    "defaultShell": string;

    /**
     * "light" | "dark" | "auto"
     */
    "theme": string;

    /**
     * interface font family name
     */
    "uiFont": string;

    /**
     * interface font size in px
     */
    "fontSize": number;

    /**
     * CJK (Chinese) font family name
     */
    "cjkFont": string;

    /**
     * Global terminal appearance defaults. Per-host values ("" / 0) fall back
     * to these; they are also where the appearance dialog persists changes
     * made in a LOCAL terminal tab (no host record to write to).
     * "" / 0 = built-in defaults (cobalt2 / Cascadia stack / 13px).
     */
    "terminalTheme": string;
    "terminalFont": string;
    "terminalFontSize": number;

    /**
     * Terminal content highlighting (http/https links, ERROR/WARN keywords).
     * Inverted flags: an older settings row without the fields keeps both
     * highlights enabled — the out-of-box default.
     */
    "disableLinkHighlight": boolean;
    "disableKeywordHighlight": boolean;

    /**
     * User-defined highlight rules: a regex and the color scheme used to
     * paint its matches. Invalid patterns are skipped by the renderer.
     */
    "highlightRules"?: HighlightRule[];

    /**
     * Quick command bar entries (Xshell 风格的快速命令): user-defined
     * scripts that one click types into the bar's target terminal sessions.
     */
    "quickCommands"?: QuickCommand[];

    /**
     * AI agent provider config (API key in SecretStore)
     */
    "llm": LLMConfig;

    /**
     * Keyboard shortcut overrides (Xshell-style). Key = command id
     * ("terminal.copy"), value = binding string ("Ctrl+Shift+C"). Only entries
     * the user changed from the default are stored; nil/empty = all defaults.
     */
    "shortcuts"?: { [_ in string]?: string };

    /**
     * Middle-click behavior on terminal panes (Xshell-style): "none" |
     * "pasteSelection" (default) | "pasteClipboard" | "sendEnter" |
     * "contextMenu".
     */
    "middleClickAction": string;

    /**
     * Host monitor panel auto-refresh interval in seconds (0 = default 60).
     */
    "monitorIntervalSeconds": number;

    /**
     * Terminal scrollback lines for NEW panes (0 = built-in default 1000).
     */
    "terminalScrollback": number;

    /**
     * Default local terminal command line (LocalShell.ID from the detected
     * catalogue; "" = system default / first detected).
     */
    "localShell": string;

    /**
     * Session logging (terminal right-click → 日志): false = enabled.
     */
    "disableSessionLog": boolean;

    /**
     * Prefix every session-log line with a HH:MM:SS timestamp.
     */
    "sessionLogTimestamps": boolean;

    /**
     * System notifications (session disconnect while the window is
     * unfocused) — false = enabled (the out-of-box default).
     */
    "disableSystemNotify": boolean;

    /**
     * AI agent runtime tunables (提示词 / 最大步数等, user-adjustable).
     */
    "agent": AgentConfig;

    /**
     * SFTP file-transfer tunables (streaming chunk size + size ceilings).
     */
    "transfer": TransferConfig;

    /**
     * Local MCP server (Phase 6) exposing host/SSH/SFTP capabilities to
     * external AI agents over streamable HTTP on 127.0.0.1.
     */
    "mcp": MCPConfig;

    /** Creates a new AppConfig instance. */
    constructor($$source: Partial<AppConfig> = {}) {
        if (!("securityMode" in $$source)) {
            this["securityMode"] = SecurityMode.$zero;
        }
        if (!("defaultShell" in $$source)) {
            this["defaultShell"] = "";
        }
        if (!("theme" in $$source)) {
            this["theme"] = "";
        }
        if (!("uiFont" in $$source)) {
            this["uiFont"] = "";
        }
        if (!("fontSize" in $$source)) {
            this["fontSize"] = 0;
        }
        if (!("cjkFont" in $$source)) {
            this["cjkFont"] = "";
        }
        if (!("terminalTheme" in $$source)) {
            this["terminalTheme"] = "";
        }
        if (!("terminalFont" in $$source)) {
            this["terminalFont"] = "";
        }
        if (!("terminalFontSize" in $$source)) {
            this["terminalFontSize"] = 0;
        }
        if (!("disableLinkHighlight" in $$source)) {
            this["disableLinkHighlight"] = false;
        }
        if (!("disableKeywordHighlight" in $$source)) {
            this["disableKeywordHighlight"] = false;
        }
        if (!("llm" in $$source)) {
            this["llm"] = (new LLMConfig());
        }
        if (!("middleClickAction" in $$source)) {
            this["middleClickAction"] = "";
        }
        if (!("monitorIntervalSeconds" in $$source)) {
            this["monitorIntervalSeconds"] = 0;
        }
        if (!("terminalScrollback" in $$source)) {
            this["terminalScrollback"] = 0;
        }
        if (!("localShell" in $$source)) {
            this["localShell"] = "";
        }
        if (!("disableSessionLog" in $$source)) {
            this["disableSessionLog"] = false;
        }
        if (!("sessionLogTimestamps" in $$source)) {
            this["sessionLogTimestamps"] = false;
        }
        if (!("disableSystemNotify" in $$source)) {
            this["disableSystemNotify"] = false;
        }
        if (!("agent" in $$source)) {
            this["agent"] = (new AgentConfig());
        }
        if (!("transfer" in $$source)) {
            this["transfer"] = (new TransferConfig());
        }
        if (!("mcp" in $$source)) {
            this["mcp"] = (new MCPConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): AppConfig {
        const $$createField11_0 = $$createType1;
        const $$createField12_0 = $$createType3;
        const $$createField13_0 = $$createType4;
        const $$createField14_0 = $$createType5;
        const $$createField22_0 = $$createType6;
        const $$createField23_0 = $$createType7;
        const $$createField24_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("highlightRules" in $$parsedSource) {
            $$parsedSource["highlightRules"] = $$createField11_0($$parsedSource["highlightRules"]);
        }
        if ("quickCommands" in $$parsedSource) {
            $$parsedSource["quickCommands"] = $$createField12_0($$parsedSource["quickCommands"]);
        }
        if ("llm" in $$parsedSource) {
            $$parsedSource["llm"] = $$createField13_0($$parsedSource["llm"]);
        }
        if ("shortcuts" in $$parsedSource) {
            $$parsedSource["shortcuts"] = $$createField14_0($$parsedSource["shortcuts"]);
        }
        if ("agent" in $$parsedSource) {
            $$parsedSource["agent"] = $$createField22_0($$parsedSource["agent"]);
        }
        if ("transfer" in $$parsedSource) {
            $$parsedSource["transfer"] = $$createField23_0($$parsedSource["transfer"]);
        }
        if ("mcp" in $$parsedSource) {
            $$parsedSource["mcp"] = $$createField24_0($$parsedSource["mcp"]);
        }
        return new AppConfig($$parsedSource as Partial<AppConfig>);
    }
}

/**
 * DockerContainer is one container row (`docker ps [-a] --format json`).
 */
export class DockerContainer {
    "id": string;
    "names": string;
    "image": string;

    /**
     * "running" | "exited" | "paused" | "created" | "restarting" | "dead"
     */
    "state": string;

    /**
     * human status incl. health/uptime ("Up 2 hours (healthy)")
     */
    "status": string;

    /**
     * "0.0.0.0:80->80/tcp, [::]:80->80/tcp"
     */
    "ports": string;
    "createdAt": string;

    /** Creates a new DockerContainer instance. */
    constructor($$source: Partial<DockerContainer> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("names" in $$source)) {
            this["names"] = "";
        }
        if (!("image" in $$source)) {
            this["image"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("ports" in $$source)) {
            this["ports"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DockerContainer instance from a string or object.
     */
    static createFrom($$source: any = {}): DockerContainer {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DockerContainer($$parsedSource as Partial<DockerContainer>);
    }
}

/**
 * DockerContainerStats is one container's live resource usage
 * (`docker stats --no-stream --format json`).
 */
export class DockerContainerStats {
    "containerId": string;
    "name": string;

    /**
     * "1.24%"
     */
    "cpuPercent": string;

    /**
     * "6.41%"
     */
    "memPercent": string;

    /**
     * "123.4MiB / 3.84GiB"
     */
    "memUsage": string;

    /**
     * "1.2kB / 3.4kB"
     */
    "netIO": string;

    /**
     * "0B / 12.6kB"
     */
    "blockIO": string;
    "pids": string;

    /** Creates a new DockerContainerStats instance. */
    constructor($$source: Partial<DockerContainerStats> = {}) {
        if (!("containerId" in $$source)) {
            this["containerId"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("cpuPercent" in $$source)) {
            this["cpuPercent"] = "";
        }
        if (!("memPercent" in $$source)) {
            this["memPercent"] = "";
        }
        if (!("memUsage" in $$source)) {
            this["memUsage"] = "";
        }
        if (!("netIO" in $$source)) {
            this["netIO"] = "";
        }
        if (!("blockIO" in $$source)) {
            this["blockIO"] = "";
        }
        if (!("pids" in $$source)) {
            this["pids"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DockerContainerStats instance from a string or object.
     */
    static createFrom($$source: any = {}): DockerContainerStats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DockerContainerStats($$parsedSource as Partial<DockerContainerStats>);
    }
}

/**
 * DockerImage is one image row (`docker images --format json`).
 */
export class DockerImage {
    "repository": string;
    "tag": string;
    "id": string;

    /**
     * "2 weeks ago"
     */
    "createdSince": string;

    /**
     * "104MB"
     */
    "size": string;

    /** Creates a new DockerImage instance. */
    constructor($$source: Partial<DockerImage> = {}) {
        if (!("repository" in $$source)) {
            this["repository"] = "";
        }
        if (!("tag" in $$source)) {
            this["tag"] = "";
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("createdSince" in $$source)) {
            this["createdSince"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DockerImage instance from a string or object.
     */
    static createFrom($$source: any = {}): DockerImage {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DockerImage($$parsedSource as Partial<DockerImage>);
    }
}

/**
 * DockerInfo is the panel overview: `docker version` server section merged
 * with the counters from `docker info`.
 */
export class DockerInfo {
    "version": string;
    "apiVersion": string;
    "osType": string;
    "arch": string;
    "kernelVersion": string;
    "containersRunning": number;
    "containersPaused": number;
    "containersStopped": number;
    "images": number;
    "dockerRootDir": string;

    /** Creates a new DockerInfo instance. */
    constructor($$source: Partial<DockerInfo> = {}) {
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("apiVersion" in $$source)) {
            this["apiVersion"] = "";
        }
        if (!("osType" in $$source)) {
            this["osType"] = "";
        }
        if (!("arch" in $$source)) {
            this["arch"] = "";
        }
        if (!("kernelVersion" in $$source)) {
            this["kernelVersion"] = "";
        }
        if (!("containersRunning" in $$source)) {
            this["containersRunning"] = 0;
        }
        if (!("containersPaused" in $$source)) {
            this["containersPaused"] = 0;
        }
        if (!("containersStopped" in $$source)) {
            this["containersStopped"] = 0;
        }
        if (!("images" in $$source)) {
            this["images"] = 0;
        }
        if (!("dockerRootDir" in $$source)) {
            this["dockerRootDir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DockerInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): DockerInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DockerInfo($$parsedSource as Partial<DockerInfo>);
    }
}

/**
 * DockerNetwork is one network row (`docker network ls --format json`).
 */
export class DockerNetwork {
    "id": string;
    "name": string;

    /**
     * "bridge" | "host" | "overlay" | "none" | …
     */
    "driver": string;

    /**
     * "local" | "swarm"
     */
    "scope": string;
    "internal": boolean;
    "ipv6": boolean;

    /** Creates a new DockerNetwork instance. */
    constructor($$source: Partial<DockerNetwork> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("driver" in $$source)) {
            this["driver"] = "";
        }
        if (!("scope" in $$source)) {
            this["scope"] = "";
        }
        if (!("internal" in $$source)) {
            this["internal"] = false;
        }
        if (!("ipv6" in $$source)) {
            this["ipv6"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DockerNetwork instance from a string or object.
     */
    static createFrom($$source: any = {}): DockerNetwork {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DockerNetwork($$parsedSource as Partial<DockerNetwork>);
    }
}

/**
 * DockerNetworkContainer is one endpoint attached to a network.
 */
export class DockerNetworkContainer {
    "name": string;
    "ipv4Address": string;
    "ipv6Address": string;

    /** Creates a new DockerNetworkContainer instance. */
    constructor($$source: Partial<DockerNetworkContainer> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("ipv4Address" in $$source)) {
            this["ipv4Address"] = "";
        }
        if (!("ipv6Address" in $$source)) {
            this["ipv6Address"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DockerNetworkContainer instance from a string or object.
     */
    static createFrom($$source: any = {}): DockerNetworkContainer {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DockerNetworkContainer($$parsedSource as Partial<DockerNetworkContainer>);
    }
}

/**
 * DockerNetworkDetail is `docker network inspect --format json`: the row
 * fields plus IPAM pools and the attached containers.
 */
export class DockerNetworkDetail {
    "id": string;
    "name": string;
    "driver": string;
    "scope": string;
    "internal": boolean;
    "enableIpv6": boolean;
    "subnets": DockerNetworkSubnet[];
    "containers": DockerNetworkContainer[];

    /** Creates a new DockerNetworkDetail instance. */
    constructor($$source: Partial<DockerNetworkDetail> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("driver" in $$source)) {
            this["driver"] = "";
        }
        if (!("scope" in $$source)) {
            this["scope"] = "";
        }
        if (!("internal" in $$source)) {
            this["internal"] = false;
        }
        if (!("enableIpv6" in $$source)) {
            this["enableIpv6"] = false;
        }
        if (!("subnets" in $$source)) {
            this["subnets"] = [];
        }
        if (!("containers" in $$source)) {
            this["containers"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DockerNetworkDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): DockerNetworkDetail {
        const $$createField6_0 = $$createType10;
        const $$createField7_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("subnets" in $$parsedSource) {
            $$parsedSource["subnets"] = $$createField6_0($$parsedSource["subnets"]);
        }
        if ("containers" in $$parsedSource) {
            $$parsedSource["containers"] = $$createField7_0($$parsedSource["containers"]);
        }
        return new DockerNetworkDetail($$parsedSource as Partial<DockerNetworkDetail>);
    }
}

/**
 * DockerNetworkSubnet is one IPAM pool of a network.
 */
export class DockerNetworkSubnet {
    "subnet": string;
    "gateway": string;

    /** Creates a new DockerNetworkSubnet instance. */
    constructor($$source: Partial<DockerNetworkSubnet> = {}) {
        if (!("subnet" in $$source)) {
            this["subnet"] = "";
        }
        if (!("gateway" in $$source)) {
            this["gateway"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DockerNetworkSubnet instance from a string or object.
     */
    static createFrom($$source: any = {}): DockerNetworkSubnet {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DockerNetworkSubnet($$parsedSource as Partial<DockerNetworkSubnet>);
    }
}

/**
 * HighlightRule is a user-defined terminal content highlight: a regular
 * expression and the color scheme used to paint its matches. The regex is
 * JavaScript-flavored (compiled in the renderer); invalid patterns are
 * ignored, never breaking the terminal.
 */
export class HighlightRule {
    "pattern": string;

    /**
     * Color scheme id from the highlight palette (red/orange/yellow/green/
     * cyan/blue/purple/pink).
     */
    "color": string;

    /** Creates a new HighlightRule instance. */
    constructor($$source: Partial<HighlightRule> = {}) {
        if (!("pattern" in $$source)) {
            this["pattern"] = "";
        }
        if (!("color" in $$source)) {
            this["color"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HighlightRule instance from a string or object.
     */
    static createFrom($$source: any = {}): HighlightRule {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HighlightRule($$parsedSource as Partial<HighlightRule>);
    }
}

/**
 * LLMConfig holds the non-sensitive LLM provider settings. The API Key is
 * stored in the OS vault (SecretStore), never here.
 * 
 * Deprecated: superseded by ModelProvider (multi-provider). Kept only so the
 * legacy single-provider config can be migrated on first run.
 */
export class LLMConfig {
    /**
     * e.g. "https://api.openai.com/v1" or a compatible endpoint
     */
    "baseUrl": string;

    /**
     * e.g. "gpt-4o", "deepseek-chat"
     */
    "model": string;

    /** Creates a new LLMConfig instance. */
    constructor($$source: Partial<LLMConfig> = {}) {
        if (!("baseUrl" in $$source)) {
            this["baseUrl"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LLMConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): LLMConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LLMConfig($$parsedSource as Partial<LLMConfig>);
    }
}

/**
 * LoginStep is one expect→send pair of a host's login script. Expect is a
 * plain substring matched against the session output ("" = don't wait);
 * Send is written to the PTY followed by a carriage return ("" = wait only).
 */
export class LoginStep {
    "expect": string;
    "send": string;

    /** Creates a new LoginStep instance. */
    constructor($$source: Partial<LoginStep> = {}) {
        if (!("expect" in $$source)) {
            this["expect"] = "";
        }
        if (!("send" in $$source)) {
            this["send"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LoginStep instance from a string or object.
     */
    static createFrom($$source: any = {}): LoginStep {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LoginStep($$parsedSource as Partial<LoginStep>);
    }
}

/**
 * MCPConfig configures the local MCP server. External agents (Claude, Codex,
 * Cursor) connect to http://127.0.0.1:<port>/mcp with the bearer Token; every
 * mutating tool call still flows through the shared PermissionGate, so the
 * user approves WRITE/DANGEROUS operations in the app just like the built-in
 * agent's.
 */
export class MCPConfig {
    "enabled": boolean;

    /**
     * Port is bound on 127.0.0.1 only; 0 falls back to DefaultMCPPort.
     */
    "port": number;

    /**
     * Token is the bearer token clients must present. Empty on first run —
     * the server generates one on first enable and persists it back.
     */
    "token": string;

    /** Creates a new MCPConfig instance. */
    constructor($$source: Partial<MCPConfig> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("token" in $$source)) {
            this["token"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MCPConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): MCPConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MCPConfig($$parsedSource as Partial<MCPConfig>);
    }
}

/**
 * MCPStatus is the runtime status of the local MCP server, shown in
 * Settings → Advanced and needed to wire external agents to it.
 */
export class MCPStatus {
    "enabled": boolean;
    "running": boolean;
    "port": number;
    "token": string;
    "url": string;

    /**
     * Error carries the last start failure (e.g. port already in use).
     */
    "error"?: string;

    /** Creates a new MCPStatus instance. */
    constructor($$source: Partial<MCPStatus> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("running" in $$source)) {
            this["running"] = false;
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("token" in $$source)) {
            this["token"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MCPStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): MCPStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MCPStatus($$parsedSource as Partial<MCPStatus>);
    }
}

/**
 * MonitorDiskUsage is one mounted filesystem's usage.
 */
export class MonitorDiskUsage {
    "device": string;
    "mount": string;
    "totalKb": number;
    "usedKb": number;
    "usedPercent": number;

    /** Creates a new MonitorDiskUsage instance. */
    constructor($$source: Partial<MonitorDiskUsage> = {}) {
        if (!("device" in $$source)) {
            this["device"] = "";
        }
        if (!("mount" in $$source)) {
            this["mount"] = "";
        }
        if (!("totalKb" in $$source)) {
            this["totalKb"] = 0;
        }
        if (!("usedKb" in $$source)) {
            this["usedKb"] = 0;
        }
        if (!("usedPercent" in $$source)) {
            this["usedPercent"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MonitorDiskUsage instance from a string or object.
     */
    static createFrom($$source: any = {}): MonitorDiskUsage {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MonitorDiskUsage($$parsedSource as Partial<MonitorDiskUsage>);
    }
}

/**
 * MonitorOverview is the host snapshot shown in the monitor panel's
 * Overview tab. Rates are computed from two samples taken ~1s apart.
 */
export class MonitorOverview {
    "cpuPercent": number;
    "cpuModel": string;
    "cpuCores": number;
    "load1": number;
    "load5": number;
    "load15": number;
    "uptimeSeconds": number;
    "kernel": string;
    "memTotalKb": number;
    "memUsedKb": number;
    "memUsedPercent": number;
    "swapTotalKb": number;
    "swapUsedKb": number;
    "disks": MonitorDiskUsage[];
    "netRxBytesPerSec": number;
    "netTxBytesPerSec": number;
    "processTotal": number;
    "processRunning": number;
    "tcpStates": MonitorTCPState[];

    /** Creates a new MonitorOverview instance. */
    constructor($$source: Partial<MonitorOverview> = {}) {
        if (!("cpuPercent" in $$source)) {
            this["cpuPercent"] = 0;
        }
        if (!("cpuModel" in $$source)) {
            this["cpuModel"] = "";
        }
        if (!("cpuCores" in $$source)) {
            this["cpuCores"] = 0;
        }
        if (!("load1" in $$source)) {
            this["load1"] = 0;
        }
        if (!("load5" in $$source)) {
            this["load5"] = 0;
        }
        if (!("load15" in $$source)) {
            this["load15"] = 0;
        }
        if (!("uptimeSeconds" in $$source)) {
            this["uptimeSeconds"] = 0;
        }
        if (!("kernel" in $$source)) {
            this["kernel"] = "";
        }
        if (!("memTotalKb" in $$source)) {
            this["memTotalKb"] = 0;
        }
        if (!("memUsedKb" in $$source)) {
            this["memUsedKb"] = 0;
        }
        if (!("memUsedPercent" in $$source)) {
            this["memUsedPercent"] = 0;
        }
        if (!("swapTotalKb" in $$source)) {
            this["swapTotalKb"] = 0;
        }
        if (!("swapUsedKb" in $$source)) {
            this["swapUsedKb"] = 0;
        }
        if (!("disks" in $$source)) {
            this["disks"] = [];
        }
        if (!("netRxBytesPerSec" in $$source)) {
            this["netRxBytesPerSec"] = 0;
        }
        if (!("netTxBytesPerSec" in $$source)) {
            this["netTxBytesPerSec"] = 0;
        }
        if (!("processTotal" in $$source)) {
            this["processTotal"] = 0;
        }
        if (!("processRunning" in $$source)) {
            this["processRunning"] = 0;
        }
        if (!("tcpStates" in $$source)) {
            this["tcpStates"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MonitorOverview instance from a string or object.
     */
    static createFrom($$source: any = {}): MonitorOverview {
        const $$createField13_0 = $$createType14;
        const $$createField18_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("disks" in $$parsedSource) {
            $$parsedSource["disks"] = $$createField13_0($$parsedSource["disks"]);
        }
        if ("tcpStates" in $$parsedSource) {
            $$parsedSource["tcpStates"] = $$createField18_0($$parsedSource["tcpStates"]);
        }
        return new MonitorOverview($$parsedSource as Partial<MonitorOverview>);
    }
}

/**
 * MonitorPort is one listening TCP socket (or a group of identical binds).
 */
export class MonitorPort {
    /**
     * "tcp" | "tcp6"
     */
    "proto": string;

    /**
     * decoded bind address
     */
    "address": string;
    "port": number;

    /**
     * sockets with this identical bind (SO_REUSEPORT etc.)
     */
    "count": number;

    /** Creates a new MonitorPort instance. */
    constructor($$source: Partial<MonitorPort> = {}) {
        if (!("proto" in $$source)) {
            this["proto"] = "";
        }
        if (!("address" in $$source)) {
            this["address"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MonitorPort instance from a string or object.
     */
    static createFrom($$source: any = {}): MonitorPort {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MonitorPort($$parsedSource as Partial<MonitorPort>);
    }
}

/**
 * MonitorProcess is one remote process with a live (sampled) CPU usage.
 */
export class MonitorProcess {
    "pid": number;
    "name": string;
    "commandLine": string;
    "cpuPercent": number;
    "rssKb": number;

    /** Creates a new MonitorProcess instance. */
    constructor($$source: Partial<MonitorProcess> = {}) {
        if (!("pid" in $$source)) {
            this["pid"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("commandLine" in $$source)) {
            this["commandLine"] = "";
        }
        if (!("cpuPercent" in $$source)) {
            this["cpuPercent"] = 0;
        }
        if (!("rssKb" in $$source)) {
            this["rssKb"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MonitorProcess instance from a string or object.
     */
    static createFrom($$source: any = {}): MonitorProcess {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MonitorProcess($$parsedSource as Partial<MonitorProcess>);
    }
}

/**
 * MonitorTCPState is one TCP connection-state histogram bucket.
 */
export class MonitorTCPState {
    /**
     * "ESTABLISHED", "LISTEN", "TIME_WAIT", …
     */
    "state": string;
    "count": number;

    /** Creates a new MonitorTCPState instance. */
    constructor($$source: Partial<MonitorTCPState> = {}) {
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MonitorTCPState instance from a string or object.
     */
    static createFrom($$source: any = {}): MonitorTCPState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MonitorTCPState($$parsedSource as Partial<MonitorTCPState>);
    }
}

/**
 * Permission tier (AGENT.md §14). READ runs silently; WRITE prompts;
 * DANGEROUS requires explicit user approval.
 */
export enum Permission {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PermissionRead = "read",
    PermissionWrite = "write",
    PermissionDangerous = "dangerous",
};

/**
 * ProxyConfig is the host's pre-SSH reachability setting (host edit form,
 * 连接 tab). Exactly one branch is meaningful per Kind:
 * 
 * 	jump   → HostID (the managed host to hop through)
 * 	http   → Addr (+ optional Username / vault password)
 * 	socks5 → Addr (+ optional Username / vault password)
 */
export class ProxyConfig {
    "kind": ProxyKind;

    /**
     * HostID names the managed host used as the jump box (jump kind only).
     * The jump box's own Proxy config, if any, is applied recursively.
     */
    "hostId"?: string;

    /**
     * Addr is the proxy address "host:port" (http / socks5 kinds).
     */
    "addr"?: string;

    /**
     * Username for authenticated proxies (http / socks5 kinds). The matching
     * password lives in the OS vault under SecretProxyPassword, never here.
     */
    "username"?: string;

    /** Creates a new ProxyConfig instance. */
    constructor($$source: Partial<ProxyConfig> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = ProxyKind.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProxyConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ProxyConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProxyConfig($$parsedSource as Partial<ProxyConfig>);
    }
}

/**
 * ProxyKind enumerates the ways a host can be reached before SSH.
 */
export enum ProxyKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * direct connection (default)
     */
    ProxyNone = "",

    /**
     * via another managed host (SSH 跳板)
     */
    ProxyJump = "jump",

    /**
     * via an HTTP CONNECT proxy
     */
    ProxyHTTP = "http",

    /**
     * via a SOCKS5 proxy
     */
    ProxySocks5 = "socks5",
};

/**
 * QuickCommand is one entry in the terminal quick command bar: a named
 * script the user can send to one or many open sessions with a single
 * click. Line breaks inside Command are delivered as carriage returns, so
 * multi-line payloads run line by line; SendEnter appends a final carriage
 * return to execute the last line immediately.
 */
export class QuickCommand {
    "id": string;
    "name": string;
    "command": string;

    /**
     * SendEnter appends \r after the payload (execute on send). Unchecked
     * entries only type the text, leaving the last line unexecuted for review.
     */
    "sendEnter": boolean;

    /** Creates a new QuickCommand instance. */
    constructor($$source: Partial<QuickCommand> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }
        if (!("sendEnter" in $$source)) {
            this["sendEnter"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuickCommand instance from a string or object.
     */
    static createFrom($$source: any = {}): QuickCommand {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QuickCommand($$parsedSource as Partial<QuickCommand>);
    }
}

/**
 * SecurityMode governs how credentials are handled (AGENT.md §10).
 */
export enum SecurityMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SecurityConvenience = "convenience",

    /**
     * default
     */
    SecurityBalanced = "balanced",
    SecuritySecure = "secure",
};

/**
 * TransferConfig holds the SFTP streaming-transfer tunables exposed in
 * global settings. Zero values mean "use the built-in default" (filled in
 * by the config service). Size ceilings exist to protect the user from
 * accidental giant transfers, not from memory pressure — transfers stream
 * with a fixed buffer regardless of file size.
 */
export class TransferConfig {
    /**
     * ChunkKB is the streaming chunk size in KB (also the progress-event
     * granularity). Default 256.
     */
    "chunkKb": number;

    /**
     * MaxUploadMB caps a single upload. Default 4096; raise it in settings
     * for effectively-unlimited transfers (0 falls back to the default).
     */
    "maxUploadMb": number;

    /**
     * MaxDownloadMB caps a single download. Default 4096.
     */
    "maxDownloadMb": number;

    /** Creates a new TransferConfig instance. */
    constructor($$source: Partial<TransferConfig> = {}) {
        if (!("chunkKb" in $$source)) {
            this["chunkKb"] = 0;
        }
        if (!("maxUploadMb" in $$source)) {
            this["maxUploadMb"] = 0;
        }
        if (!("maxDownloadMb" in $$source)) {
            this["maxDownloadMb"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TransferConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): TransferConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TransferConfig($$parsedSource as Partial<TransferConfig>);
    }
}

/**
 * TunnelConfig is a per-host SSH tunnel definition, edited in the host
 * settings and persisted with the host (no secrets inside — the tunnel
 * authenticates with the host's credentials).
 */
export class TunnelConfig {
    "enabled": boolean;
    "type": TunnelType;

    /**
     * local/dynamic: local machine; remote: the SSH server
     */
    "listenPort": number;

    /**
     * Listen bind address: the local machine for local/dynamic, the server
     * for remote. "" = 127.0.0.1 (only the tunnel's own machine); "0.0.0.0"
     * exposes the listener to the network.
     */
    "bindHost"?: string;

    /**
     * Forward target. local: resolved from the SERVER's side (e.g. its
     * loopback MySQL); remote: resolved from the LOCAL machine's side.
     */
    "targetHost"?: string;
    "targetPort"?: number;

    /** Creates a new TunnelConfig instance. */
    constructor($$source: Partial<TunnelConfig> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("type" in $$source)) {
            this["type"] = TunnelType.$zero;
        }
        if (!("listenPort" in $$source)) {
            this["listenPort"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TunnelConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): TunnelConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TunnelConfig($$parsedSource as Partial<TunnelConfig>);
    }
}

/**
 * TunnelState is the lifecycle state of a running (or attempted) tunnel.
 */
export enum TunnelState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * not running (never started or stopped by user)
     */
    TunnelStopped = "stopped",

    /**
     * dialing the first connection
     */
    TunnelStarting = "starting",

    /**
     * SSH up, listener serving
     */
    TunnelConnected = "connected",

    /**
     * connection lost; backing off before redial
     */
    TunnelReconnecting = "reconnecting",

    /**
     * fatal setup problem (e.g. port already in use)
     */
    TunnelError = "error",
};

/**
 * TunnelStatus is the manager's view of one host's tunnel — pushed to the
 * frontend on every change and returned by ListTunnels. One host can have
 * several; Key identifies the rule within the host.
 */
export class TunnelStatus {
    "hostId": string;
    "hostName": string;

    /**
     * rule identity (TunnelConfig.Key)
     */
    "key": string;
    "config": TunnelConfig;
    "state": TunnelState;

    /**
     * human-readable, shown in the panel
     */
    "lastError"?: string;

    /**
     * consecutive failed dials in the current cycle
     */
    "retries": number;

    /** Creates a new TunnelStatus instance. */
    constructor($$source: Partial<TunnelStatus> = {}) {
        if (!("hostId" in $$source)) {
            this["hostId"] = "";
        }
        if (!("hostName" in $$source)) {
            this["hostName"] = "";
        }
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("config" in $$source)) {
            this["config"] = (new TunnelConfig());
        }
        if (!("state" in $$source)) {
            this["state"] = TunnelState.$zero;
        }
        if (!("retries" in $$source)) {
            this["retries"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TunnelStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): TunnelStatus {
        const $$createField3_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField3_0($$parsedSource["config"]);
        }
        return new TunnelStatus($$parsedSource as Partial<TunnelStatus>);
    }
}

/**
 * TunnelType selects how an SSH tunnel exposes a network on the far side —
 * the three forms Xshell offers (AGENT.md §16.5).
 */
export enum TunnelType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * TunnelLocal forwards a local listen port to (TargetHost, TargetPort)
     * as seen from the SSH server — `ssh -L`. Use-case: reach a database or
     * web panel bound to the server's internal/loopback interface.
     */
    TunnelLocal = "local",

    /**
     * TunnelRemote is the reverse: the SSH SERVER listens on
     * (BindHost, ListenPort) and every connection there is carried back to
     * (TargetHost, TargetPort) as seen from the local machine — `ssh -R`.
     * Use-case: expose a service running on your machine to the server (or
     * its network).
     */
    TunnelRemote = "remote",

    /**
     * TunnelDynamic exposes a SOCKS5 proxy on (BindHost, ListenPort) whose
     * connects originate from the SSH server — `ssh -D`.
     */
    TunnelDynamic = "dynamic",
};

// Private type creation functions
const $$createType0 = HighlightRule.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = QuickCommand.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = LLMConfig.createFrom;
const $$createType5 = $Create.Map($Create.Any, $Create.Any);
const $$createType6 = AgentConfig.createFrom;
const $$createType7 = TransferConfig.createFrom;
const $$createType8 = MCPConfig.createFrom;
const $$createType9 = DockerNetworkSubnet.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = DockerNetworkContainer.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = MonitorDiskUsage.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = MonitorTCPState.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = TunnelConfig.createFrom;
