// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * LocalShell is one detected command line available for local terminals.
 */
export class LocalShell {
    /**
     * ID is stable and used as the AppConfig.LocalShell value ("pwsh",
     * "powershell", "cmd", "wsl", "gitbash", "bash", "zsh", "fish", "sh"…).
     */
    "id": string;

    /**
     * Name is the display label ("PowerShell", "WSL", …).
     */
    "name": string;

    /**
     * Program is the resolved executable path to spawn.
     */
    "program": string;

    /**
     * Args are the shell's startup arguments (UTF-8 bootstrap, login flag…).
     */
    "args": string[];

    /** Creates a new LocalShell instance. */
    constructor($$source: Partial<LocalShell> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("program" in $$source)) {
            this["program"] = "";
        }
        if (!("args" in $$source)) {
            this["args"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalShell instance from a string or object.
     */
    static createFrom($$source: any = {}): LocalShell {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("args" in $$parsedSource) {
            $$parsedSource["args"] = $$createField3_0($$parsedSource["args"]);
        }
        return new LocalShell($$parsedSource as Partial<LocalShell>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
