// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LocalShell is one detected command line available for local terminals.
 */
export interface LocalShell {
    /**
     * ID is stable and used as the AppConfig.LocalShell value ("pwsh",
     * "powershell", "cmd", "wsl", "gitbash", "bash", "zsh", "fish", "sh"…).
     */
    "id": string;

    /**
     * Name is the display label ("PowerShell", "WSL", …).
     */
    "name": string;

    /**
     * Program is the resolved executable path to spawn.
     */
    "program": string;

    /**
     * Args are the shell's startup arguments (UTF-8 bootstrap, login flag…).
     */
    "args": string[] | null;
}
