import { useEffect, useState } from "react";

import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { SECURITY_MODE_LABELS } from "@/features/settings/api";
// Bindings generated by Wails from the Go ConfigService. AppConfig and
// SecurityMode types come from the domain package.
import { ConfigService } from "@/../bindings/github.com/ai-remote/workspace/internal/interfaces";
import {
  SecurityMode,
  type AppConfig,
} from "@/../bindings/github.com/ai-remote/workspace/internal/domain/models";

const DEFAULT_CONFIG: AppConfig = {
  securityMode: SecurityMode.SecurityBalanced,
  defaultShell: "/bin/bash",
  theme: "dark",
};

/**
 * Settings view. Phase 1: read-only display of the app config fetched from the
 * Go ConfigService — this exercises the end-to-end Wails binding path
 * (frontend → generated TS → Go service → SQLite-stored settings).
 * Editing lands with the Host/connection work in Phase 2.
 */
export function SettingsView() {
  const [config, setConfig] = useState<AppConfig>(DEFAULT_CONFIG);
  const [loaded, setLoaded] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    ConfigService.GetAppConfig()
      .then((res: AppConfig) => {
        if (!cancelled) {
          setConfig(res);
          setLoaded(true);
        }
      })
      .catch((err: unknown) => {
        if (!cancelled) {
          setError(err instanceof Error ? err.message : String(err));
          setLoaded(true);
        }
      });
    return () => {
      cancelled = true;
    };
  }, []);

  return (
    <div className="mx-auto max-w-2xl p-8">
      <h1 className="text-xl font-semibold tracking-tight">Settings</h1>
      <p className="mt-1 text-sm text-muted-foreground">
        Application configuration, stored locally.
      </p>

      <Card className="mt-6">
        <CardHeader>
          <CardTitle className="text-base">Security Mode</CardTitle>
          <CardDescription>
            Controls how credentials are stored and whether connections
            auto-connect (AGENT.md §10).
          </CardDescription>
        </CardHeader>
        <CardContent>
          <span className="inline-flex rounded-full border border-border bg-muted px-3 py-1 text-sm">
            {SECURITY_MODE_LABELS[config.securityMode] ?? config.securityMode}
          </span>
        </CardContent>
      </Card>

      <Card className="mt-4">
        <CardHeader>
          <CardTitle className="text-base">Runtime</CardTitle>
          <CardDescription>Local shell and theme preferences.</CardDescription>
        </CardHeader>
        <CardContent>
          <dl className="grid grid-cols-2 gap-y-2 text-sm">
            <dt className="text-muted-foreground">Default shell</dt>
            <dd className="font-mono">{config.defaultShell}</dd>
            <dt className="text-muted-foreground">Theme</dt>
            <dd>{config.theme}</dd>
          </dl>
        </CardContent>
      </Card>

      <p className="mt-6 text-xs text-muted-foreground">
        {error
          ? `Could not load config from backend (${error}). Showing defaults.`
          : loaded
            ? "Loaded from local store."
            : "Loading…"}
      </p>
    </div>
  );
}
