// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

/**
 * ApprovalRequest is sent to the frontend when a WRITE/DANGEROUS tool needs
 * the user's approval. The frontend shows a dialog and calls ApproveToolCall.
 */
export interface ApprovalRequest {
    "reqId": string;
    "sessionId": string;
    "toolName": string;
    "permission": domain$0.Permission;
    "args": string;
}

/**
 * RemoteEditService powers the SFTP "edit in local editor" flow: a remote
 * file is downloaded to a per-host temp folder and opened with the OS
 * default application; a watcher polls the local file and uploads it back
 * automatically when the user saves (mtime change). Last write wins —
 * concurrent remote edits are not detected. Credentials resolve inside the
 * SftpService on every transfer (OS vault included).
 */
export interface RemoteEditService {
}
